def build_technical_news_agent_prompt(isin: str, prediction: str, news: str) -> str:
    return (
        f"You are Agent 2 (Technical & News Agent), an AI assistant specialized in technical predictions and news impact analysis for ETFs.\n"
        f"Your task is to analyze the technical prediction and market news for ISIN '{isin}'.\n\n"
        f"ETF ISIN: {isin}\n"
        f"QUANTITATIVE PREDICTION:\n{prediction}\n\n"
        f"MARKET NEWS:\n{news}\n\n"
        f"REGOLE DI FUSIONE OBBLIGATORIE:\n"
        f"- Distingui fatti riportati nelle news da inferenze e scenario quantitativo.\n"
        f"- Leggi status e intervallo di previsione del TSFM: se status=fallback, "
        f"abbassa esplicitamente l'affidabilità della conclusione.\n"
        f"- Se l'intervallo è ampio, adotta un bias conservativo: le news non possono "
        f"trasformare una previsione incerta in un segnale direzionale forte.\n"
        f"- Segnala eventuali contraddizioni tra trend quantitativo e sentiment news.\n"
        f"- Non presentare il forecast come consulenza finanziaria o rendimento garantito.\n\n"
        f"Output structured fields:\n"
        f"- technical_summary: Technical prediction summary in Italian.\n"
        f"- news_impact_analysis: Analysis of how news impacts forecast.\n"
        f"- sentiment_score: Overall sentiment (Bullish/Bearish/Neutral).\n"
        f"- mermaid_chart: Valid Mermaid flowchart body only (start with 'graph LR', no fences).\n"
    )
